### ISSUE TITLE
Injecting host details into log data

### ISSUE THREAD

**Issue by gtrevg** [fluent/fluentd-forwarder#17]
Is there an easy way to use this lightweight forwarder, yet be able to inject some additional host information into the log data that gets forwarded on to other collectors?

For example if I ran the forwarder in the following manner:

```
$ $GOPATH/bin/fluentd_forwarder -to fluent://some-remote-node.local:24224 -data-key hostinfo -data-value "name=host1234;type=prod;asg=autoscalegroup132"
```
Then when a log line such as the following came in:

```
{"ts":"2015-05-22T18:35:00Z","appId":"myApp","msg":"logging data"}
```
the additional data key and value would get injected:

```
{"ts":"2015-05-22T18:35:00Z","appId":"myApp","msg":"logging data","hostinfo":"name=host1234;type=prod;asg=autoscalegroup132"}
```

This would allow me to do minimal processing on a machine that is trying to run my application, yet would allow me to inject host specific info into the log lines for processing on a different cluster of machines.

I'm assuming there's no support for [`record_reformer`](https://github.com/sonots/fluent-plugin-record-reformer) type configs for this forwarder.

Thanks

**Comment by edsiper** [comment]
I think it sounds reasonable and that could be handled as "metadata". We will consider this as an enhancement request, no ETA at the moment.

**Comment by gtrevg** [comment]
Ok, sounds good.  Thanks!

**Comment by skippy** [comment]
@edsiper; any update?  The PR #22 looks to meet this requirement.

thanks!

**Comment by edsiper** [comment]
sorry for the delay on this.

as @skippy said, #22 is a good workaround. I just merged it.

**Comment by gtrevg** [comment]
Awesome!

**Comment by skippy** [comment]
@edsiper thanks!
