### ISSUE TITLE
Problem running under go 1.7.1+

### ISSUE THREAD

**Issue by tuxtek** [fluent/fluentd-forwarder#27]
As the below error indicates, this is not working with go 1.7.1.

# github.com/fluent/fluentd-forwarder/entrypoints/fluentd_forwarder
link: warning: option -X main.progVersion 0.0.1 may not work in future releases; use -X main.progVersion=0.0.1

**Comment by pnovotnak** [comment]
Yep;

# github.com/fluent/fluentd-forwarder/entrypoints/fluentd_forwarder
/usr/local/Cellar/go/1.7.4_1/libexec/pkg/tool/darwin_amd64/link: -X flag requires argument of the form importpath.name=value
build: exit status 2
