### ISSUE TITLE
README missing dependency

### ISSUE THREAD

**Issue by EVODelavega** [fluent/fluentd-forwarder#28]
The readme file doesn't mention the dependency on github.com/treasure-data/td-client-go, which needs to be installed, as can be seen in the `.travis.yml` file.

**Comment by cosmo0920** [comment]
https://github.com/fluent/fluentd-forwarder/pull/21 can solve this?

**Comment by EVODelavega** [comment]
@cosmo0920 Didn't see that PR, but yeah, that's all that was needed
